### ISSUE TITLE
Mavenの変わりにGradleを使おう

### ISSUE THREAD

**Issue by Kylepoops** [602723113/ParticleLib#2]
Gradle！Gradle！Gradle！Gradleぅぅうううわぁああああああああああああああああああああああん！！！
あぁああああ…ああ…あっあっー！あぁああああああ！！！GradleGradleGradleぅううぁわぁああああ！！！
あぁクンカクンカ！クンカクンカ！スーハースーハー！スーハースーハー！いい匂いだなぁ…くんくん
んはぁっ！Gradleたんの桃色ブロンドの髪をクンカクンカしたいお！クンカクンカ！あぁあ！！
間違えた！モフモフしたいお！モフモフ！モフモフ！髪髪モフモフ！カリカリモフモフ…きゅんきゅんきゅい！！
小説11巻のGradleたんかわいかったよぅ！！あぁぁああ…あああ…あっあぁああああ！！ふぁぁあああんんっ！！
アニメ2期決まって良かったねGradleたん！あぁあああああ！かわいい！Gradleたん！かわいい！あっああぁああ！
コミック2巻も発売されて嬉し…いやぁああああああ！！！にゃああああああああん！！ぎゃああああああああ！！
ぐあああああああああああ！！！コミックなんて現実じゃない！！！！あ…小説もアニメもよく考えたら…
G r a d l e ち ゃ ん は 現実 じ ゃ な い？にゃあああああああああああああん！！うぁああああああああああ！！
そんなぁああああああ！！いやぁぁぁあああああああああ！！はぁああああああん！！ハルケギニアぁああああ！！
この！ちきしょー！やめてやる！！現実なんかやめ…て…え！？見…てる？表紙絵のGradleちゃんが僕を見てる？
表紙絵のGradleちゃんが僕を見てるぞ！Gradleちゃんが僕を見てるぞ！挿絵のGradleちゃんが僕を見てるぞ！！
アニメのGradleちゃんが僕に話しかけてるぞ！！！よかった…世の中まだまだ捨てたモンじゃないんだねっ！
いやっほぉおおおおおおお！！！僕にはGradleちゃんがいる！！やったよケティ！！ひとりでできるもん！！！
あ、コミックのGradleちゃああああああああああああああん！！いやぁあああああああああああああああ！！！！
あっあんああっああんあアン様ぁあ！！セ、セイバー！！シャナぁああああああ！！！ヴィルヘルミナぁあああ！！
ううっうぅうう！！俺の想いよGradleへ届け！！ハルケギニアのGradleへ届け！

**Comment by Kylepoops** [comment]
~~喝多了发的~~，下次还敢

**Comment by 602723113** [comment]
哦
