### ISSUE TITLE
PolarEquationRenderer bug fix

### ISSUE THREAD

**Issue by Mottle** [602723113/ParticleLib#6]
极坐标方程渲染器的minTheta、maxTheta、dTheta似乎都没有转换为弧度

![角度?](https://github.com/602723113/ParticleLib/assets/21277831/48209da2-fe53-4ae9-9fed-659bf33a85c6)

![图片](https://github.com/602723113/ParticleLib/assets/21277831/824aba73-d99e-4df9-9b14-3fc37f40f3d3)

**Comment by Mottle** [comment]
![图片](https://github.com/602723113/ParticleLib/assets/21277831/4e6b4379-057d-49dd-9f3d-3ca6329630b4)
没有转换为弧度

**Comment by 602723113** [comment]
已知悉，并在下版本修复
